---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
              name: plaintext
            - containerPort: 9999
              name: jmx
          resources:
            requests:
              cpu: 80m
              memory: 350Mi
            limits:
              cpu: 100m
              memory: 400Mi
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-service-1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_CREATE_TOPICS
              value: "spring-kafka-test"
            - name: JMX_PORT
              value: "9999"
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=127.0.0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: plaintext
    - port: 9999
      name: jmx
  clusterIP: None
  selector:
    app: kafka
