---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-kafka-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-kafka-test
    spec:
      containers:
        - name: app
          image: nikulesko/spring-kafka-test:1.2
          env:
              - name: KAFKA_TOPIC
                value: "spring-kafka-test"
              - name: KAFKA_PATH
                value: "kafka-service-1:9092"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 150m
              memory: 1Gi
            limits:
              cpu: 200m
              memory: 1.9Gi

---

apiVersion: v1
kind: Service
metadata:
  name: spring-kafka-test
spec:
  selector:
    app: spring-kafka-test
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080